version: '3'
services:
  fridgesim:
    build: .
    tty: true
    environment:
      - FRIDGESIM_PORT=8080
      - FRIDGESIM_DBHOST=db
      - FRIDGESIM_DBPORT=5432
      - FRIDGESIM_DBUSER=postgres
      - FRIDGESIM_DBPASSWORD=pass
    ports:
      - 8080:8080
  db:
    image: postgres:14
    tty: true
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=fridgesim
volumes:
  db_volume:
