package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
)

// Ingredient holds the schema definition for the Ingredient entity.
type Ingredient struct {
	ent.Schema
}

// Fields of the Ingredient.
func (Ingredient) Fields() []ent.Field {
	return []ent.Field{
		// NOTE: if you want to set id generated by app, it should be defined explicitly
		// https://entgo.io/docs/schema-fields/#id-field
		field.String("id").
			MaxLen(26).
			NotEmpty().
			Unique().
			Immutable(),
		field.String("kind"),
		field.Float("amount"),
	}
}

// Edges of the Ingredient.
func (Ingredient) Edges() []ent.Edge {
	return nil
}
